### PR TITLE
Update delegates.json

### PR DESCRIPTION
**Pull request by gagichce**
## Description
**TAO Miner's Union - LOCAL 127.0.0.1**

TAO Miner's Union Crest

A joint council focused on collective efficiency and security of operators on Bittensor. The largest and strongest voice for miners. We are the other 41%.

## Review Checklist
- [ ] All CircleCI checks below are green.
- [x] Only one delegate is modified.

### CODE REVIEW

**Comment by gagichce** [comment]
I know this file will be deprecated soon in place of on-chain identity.. but posting here as well just in case.

**Review by IvanAnishchuk — APPROVED** [review]
Can we please move forward with this? Unless decided not to in which case how could we help with the on-chain identities? 

It makes our community effort here look worse than more established validators and makes it harder to attract additional stake which is required for stable operations. We are supposed to be permissionless community, come on, guys.

**Review by HudsonGraeme — APPROVED** [review]
LGTM 🥩

**Comment by alex-drocks** [comment]
Data is valid

**Comment by HudsonGraeme** [comment]
Thanks for the merge @unconst

**Comment by IvanAnishchuk** [comment]
image

**Pull request merged**
